version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - '8005:8005'  # Порт сервера FastAPI

  client:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '3007:3007'  # Порт React-приложения
