version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - '8003:8003'  # Порт сервера FastAPI

  client:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - '3000:3000'  # Порт React-приложения
  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/deafult.conf
